export interface Problem {
  id?: number; // optional, will be auto-generated by IndexedDB
  url: string;
  n: number; // repetition count
  ef: number; // easiness factor
  lastReview: number; // timestamp (ms)
  nextDue: number; // timestamp (ms)
} 